name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - mamba=2.5.0
  - numpy=2.3.5
  - pandas=3.0.0
  - xarray
  - netcdf4=1.7.4
  - packaging=26.0
  - gmt=6.6.0
  - pygmt=0.18.0
  - ghostscript=10.06.0
  - geopandas=1.1.2
  - rioxarray=0.21.0
  - xarray-spatial=0.5.2
  - polars=1.37.1
  - seaborn=0.13.2
  - plotnine=0.15.3
  - great_tables=0.20.0
  - plotly=6.5.2
  - pingouin=0.5.5
  - gstools=1.7.0
  - pykrige=1.7.3
  - pyrolite=0.3.6
  - mplstereonet=0.6.3
  - leafmap=0.59.0
  - mpltern=1.0.4
  - scikit-posthocs=0.11.4
  - contextily=1.7.0
  - verde=1.8.1
  - proj=9.7.1
  # - proj-data=1.24
  - pyproj=3.7.2
  - pip=26.0
  - pip:
      - geostatspy==0.0.79
      - marginaleffects==0.3.0
      - pycircstat2==0.1.15
      - sphstat==1.0.6
      - statistics==1.0.3.5
